### ISSUE TITLE
Dropbox link to download test bam file is broken

### ISSUE THREAD

**Issue by deloger** [InstitutCurie/SV-Bay#3]
Hi, the dropbox link to download test bam file is broken, here below the message from dropbox :
"Ce fichier ne se trouve plus ici.
Quelqu'un a peut-être supprimé le fichier ou désactivé le lien."

Best regards

**Comment by dashainparis** [comment]
Thank you for mention it, I've changed the link, now it works. Please also update the code I made some changes in it.
